### ISSUE TITLE
error: E: Unable to locate package git

### ISSUE THREAD

**Issue by ludoch** [hughperkins/howto-jenkins-ssl#2]
Getting this error:
~/howto-jenkins-ssl/docker$ sudo docker build -t letsencrypt .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
6c953ac5d795: Pull complete 
3eed5ff20a90: Pull complete 
f8419ea7c1b5: Pull complete 
51900bc9e720: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:97421885f3da3b23f52eeddcaa9f8f91172a8ac3cd5d3cd40b51c7aad09f66cc
Status: Downloaded newer image for ubuntu:14.04
 ---> 8f1bd21bd25c
Step 2 : RUN apt-get install -y git bash-completion dnsutils nginx telnet lsof
 ---> Running in e228a7b3392e
Reading package lists...
Building dependency tree...
Reading state information...
Package bash-completion is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  bash
E: Unable to locate package git
E: Package 'bash-completion' has no installation candidate
E: Unable to locate package dnsutils
E: Unable to locate package nginx
E: Unable to locate package telnet
E: Unable to locate package lsof
The command '/bin/sh -c apt-get install -y git bash-completion dnsutils nginx telnet lsof' returned a non-zero code: 100

**Comment by ludoch** [comment]
Maybe missing a RUN apt-get update in the 2nd line.

**Comment by hughperkins** [comment]
Added.  Can you check whether that works for you now?  (strangely, the old one works for me, which casts doubt on my theory that if something works in one docker instance, it will work on all the others...)

**Comment by hughperkins** [comment]
(Hmmm, that installs ton of stuff now :-P   I might dabble in seeing if it runs from `ubuntu:16.04`)
